//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA_BugTrackerSystemC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Theme { get; set; }
        public string Type { get; set; }
        public string Priority { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
